### ISSUE TITLE
Unable to Run BenchTool from QtCreator

### ISSUE THREAD

**Issue by sivachaitanya** [OracleChain/EOSBenchTool#2]
I have download QT5.9.6 and as mentioned in the instructions I have  open Qt Creator and choose "Open Project", select the "src/EOSBenchTool.pro" and open and when I click Run from the Build menu it displays error "/home/ubuntu/Documents/EOSBenchTool/src/account/createaccount.h:10: error: codebase/chain/signedtransaction.h: No such file or directory" ?

**Comment by spartucus** [comment]
Sorry for the late reply, it seems like that your projects are missing `chainkit` submodule.
How did you download the project?  You can either using 
```
git clone --recurse-submodules https://github.com/OracleChain/EOSBenchTool.git
```
or 
```
git clone https://github.com/OracleChain/EOSBenchTool.git
cd EOSBenchTool
git submodule init
git submodule update
```
