### ISSUE TITLE
Create account failed

### ISSUE THREAD

**Issue by sivachaitanya** [OracleChain/EOSBenchTool#3]
As mentioned in the settings I have initalised the values and in the Benchmark Testing tab, when I click prepare the following error regarding accounts is observed - 

Start creating 8 accounts ...
Create lsf14 failed.
Create whozm failed.
Create 35orx failed.
Create n2fof failed.
Create my2po failed.
Create wtg5d failed.
Create q3hhc failed.
Create lt44q failed.
Create account failed, maybe accounts already exists, try again!

**Comment by spartucus** [comment]
Have you set creator's name and private key? This should be done by all set up. I'm closing the issue, feel free to reopen it while you still have the problem.

**Comment by nemu90** [comment]
I got the same error 

debug 2019-01-04T09:54:20.818 thread-0  http_plugin.cpp:581           handle_exception     ] Exception Details: 10 assert_exception: Assert Exception
pivot != std::string::npos: No delimiter in string, cannot determine data type: 
    {"str":""}
    thread-0  public_key.cpp:44 parse_base58

**Comment by nemu90** [comment]
Not really sure because of this https://github.com/EOSIO/eosjs-ecc/issues/11 or not.
