### ISSUE TITLE
EOSBenchTool does NOT work on windows10 or MAC?

### ISSUE THREAD

**Issue by FudanJinLi** [OracleChain/EOSBenchTool#4]
When I run EOSBenchTool on Win10, an error occurs that it can NOT create accounts(create [Account] failed). However, EOS works well and I have NOT published the system contracts.
I have set contract, created token and issued token as preparation, and all succeed.
When I run EOSBenchTool on MAC with the same configuration on Win10, it can create accounts. However, an other error occurs that it can NOT transfer, and the program always shows "Transferring".
How can I solve this and let the Tool run?

**Comment by spartucus** [comment]
You need set super account and its private key, like `eosio`. EOSBenchTool use developmet mode to create account, that said we use something like `cleos create account eosio NEW_ACCOUNT KEY KEY`, not release mode like `cleos system newaccount`. Hope this helps.

**Comment by spartucus** [comment]
close this for now, feel free to reopen it if you still have issues.
